### ISSUE TITLE
changes may have broken this?

### ISSUE THREAD

**Issue by ngzax** [h5gq3/graph-query#3]
I just installed via dojo and that app failed to build:

```
kiln: finding ship and desk from %graph-query on ~nortex-ramnyd to %home
> |sync %home ~nortex-ramnyd %graph-query
>=
; ~nortex-ramnyd is your neighbor
gall: not running %graph-query-cli yet, got %watch
> |start %graph-query-cli
>=
activated app home/graph-query-cli
gall: failed to build agent %graph-query-cli
> +graph-query [~winter-paches %the-great-north] ~ `~winter-paches `~2021.4.28 `~2021.4.10 1
/gen/graph-query/hoon
%generator-build-fail
```

Perhaps the latest %graph-store changes have broken it? Unfortunately, I am not sufficiently skilled to look into fixing. Sorry.

**Comment by h5gq3** [comment]
yeah, seems graph-store updates broke this. I should fix it

**Comment by ngzax** [comment]
thanks. obviously not urgent, just wanted to let you know since I ran across it while working on the ruby eyrelock. this commit has some helpful hints on the changes, though I don't know if it helps at the hoon level. 

https://github.com/ryjm/urbit-api.el/commit/5a1b7f9e012735c1223727b652e321e805d8099a

**Comment by h5gq3** [comment]
just tested and it works on my ship actually
are all /src hoon files actually on your ship? I think the |sync is not working

**Comment by ngzax** [comment]
i think you are correct. the files aren't there... and when i tried to sync again i saw this:

```
kiln: already syncing from %graph-query on ~nortex-ramnyd to %home
> |sync %home ~nortex-ramnyd %graph-query
```

indicating that it still thinks the initial sync all those months ago is still running? i'll try to see what's up with |sync.
